[package]
name = "ka-pi"
version = "0.0.1"
edition = "2021"
authors = ["ChAoS-UnItY"]
description = "A JVM Bytecode Manipulation Framework inspired by ASM."
license = "MIT"
repository = "https://github.com/ChAoSUnItY/Ka-Pi/"
readme = "README.md"
keywords = ["jvm", "jvm-bytecode", "bytecode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = { version = "0.21.0", features = ["invocation"] }
unicode-segmentation = "1.10.1"
lazy_static = "1.4.0"
rstest = "0.16.0"

[features]
reflection = []
default = []
