[package]
name = "ka-pi"
version = "0.0.1"
edition = "2021"
authors = ["ChAoS-UnItY"]
description = "A JVM Bytecode Manipulation Framework inspired by ASM."
license = "MIT"
repository = "https://github.com/ChAoSUnItY/Ka-Pi/"
readme = "README.md"
keywords = ["jvm", "jvm-bytecode", "bytecode", "bytecode-manipulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ka_pi"
path = "src/lib.rs"

[[test]]
name = "compile_class_file"
path = "test/compile_class_file.rs"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
unicode-segmentation = "1.10.1"
lazy_static = "1.4.0"
either = "1.8.1"
itertools = "0.10.5"
num_enum = "0.6.0"
indexmap = { version = "1.9.3", features = ["serde-1"] }
nom = "7.1.3"
cesu8 = "1.1.0"
strum = { version = "0.24.1", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.28.0", features = ["yaml"] }
rstest = "0.17.0"

[features]
default = ["parse"]
parse = []
generate = []
