[package]
name = "ka-pi"
version = "0.1.0"
edition = "2021"
authors = ["ChAoS-UnItY"]
description = "A JVM Bytecode Manipulation Framework inspired by ASM."
license = "MIT"
repository = "https://github.com/ChAoSUnItY/Ka-Pi/"
readme = "README.md"
keywords = ["jvm", "jvm-bytecode", "bytecode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ka_pi"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
lazy_static = "1.4.0"
either = "1.8.1"
itertools = "0.11.0"
num_enum = "0.6.0"
cesu8 = "1.1.0"
strum = { version = "0.25.0", features = ["derive"] }
aquamarine = "0.3.2"
paste = "1.0.13"
bitflags = { version = "2.3.3", features = ["serde"] }
thiserror = "1.0.43"
byteorder = "1.4.3"

[dev-dependencies]
insta = { version = "1.28.0", features = ["yaml"] }
rstest = "0.18.1"
criterion = { version = "0.5.1", features = ["html_reports"] }

[features]
default = ["parse", "serde_span"]
parse = []
serde_span = []

[[bench]]
name = "parse"
harness = false
