flowchart
    A0[(Entry Point)]
    A1["< Self as FormalTypeParameterVisitable>::visit_parameter_types"]
    A2["< Self as FormalTypeParameterVisitable>::visit_parameter_type"]
    A3[visit_super_class]
    A4[visit_interfaces]
    A5[visit_interface]
    
    A0 --> A1 --> A2 --> A3 --> A4 --> A5