flowchart
    A0[(Entry Point)]
    A1["< Self as FormalTypeParameterVisitable>::visit_parameter_types"]
    A2["< Self as FormalTypeParameterVisitable>::visit_parameter_type"]
    A3[visit_parameter_types]
    A4[visit_parameter_type]
    A5[visit_return_type]
    A6[visit_exception_types]
    A7[visit_exception_type]
    
    A0 --> A1 --> A2 --> A3 --> A4 --> A5 --> A6 --> A7