flowchart
    TV_TYP_REF{ReferenceType}
    TV_TYP_SIG{SignatureType}
    TV_TYP_THR{ThrowsType}
    TV_TYP_BAS{BaseType}
    TV_TYP_ARR{ArrayType}
    TV_TYP_CLS{ClassType}
    TV_TYP_TYP_VAR{TypeVariable}

    TV_A1[visit_base_type]
    TV_A2[visit_class_type]
    TV_A3[visit_array_type]
    TV_A4[visit_type_variable]
    TV_B0[visit_type_arguments]
    TV_B1[visit_type_argument]
    TV_B2[visit_type_argument_bound]
    TV_B3[visit_type_argument_wildcard]
    TV_C0[visit_inner_classes]
    TV_C1[visit_inner_class]

    TV_TYP_REF & TV_B2 & TV_A3 --> TV_TYP_CLS
    TV_TYP_SIG & TV_TYP_THR --> TV_TYP_REF

    TV_TYP_SIG & TV_A3 --> TV_TYP_BAS
    TV_TYP_REF --> TV_TYP_ARR
    
    TV_TYP_BAS --> TV_A1
    TV_TYP_ARR --> TV_A3
    TV_TYP_CLS --> TV_A2
    TV_TYP_TYP_VAR --> TV_A4

    TV_A2 --> TV_B0
    TV_B0 --> TV_B1
    TV_B1 --> TV_B3
    TV_B1 --> TV_B2
    TV_B2 --> TV_A3 & TV_TYP_TYP_VAR

    TV_A2 --> TV_C0
    TV_C0 --> TV_C1
    TV_C1 --> TV_B0
    TV_C1 --> TV_C1

    TV_TYP_REF --> TV_TYP_TYP_VAR
    TV_TYP_THR --> TV_TYP_TYP_VAR