name: Pull Request CI

on: [pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Format check
        run: cargo fmt --check
      - name: Check build (Strict) (Skipped at this moment)
        if: ${{ false }}
        run: cargo build --verbose --release --features "strict"
      - name: Run tests
        run: cargo test --verbose